- id: msk-homelab1
  domains:
    - id: rip
      name: tie.rip
  hosts:
    - id: eerie
      name: eerie
      addresses:
        - id: lan
          value: 2a02:2168:8f97:3000::1
        - id: wan
          value: 2a02:2168:a0f:bc67::1
    - id: madara
      name: madara
      addresses:
        - id: lan
          value: 2a02:2168:8f97:3000::469
        - id: wlan
          value: 2a02:2168:8f97:3004::1
    - id: akane
      name: akane
      addresses:
        - id: lan
          value: 2a02:2168:8f97:3000::6da
    - id: saitama
      name: saitama
      addresses:
        - id: lan
          value: 2a02:2168:8f97:3000::ffb
    - id: kazuma
      name: kazuma
      addresses:
        - id: lan
          value: 2a02:2168:8f97:3000::d07

  aliases:
    - id: root
      host: saitama.@
    - id: jellyfin
      name: jellyfin
      host: saitama.@
    - id: sonarr
      name: sonarr
      host: saitama.@
    - id: flood
      name: flood
      host: saitama.@
    - id: jackett
      name: jackett
      host: saitama.@
    - id: brim
      name: brim
      host: join.brim.su

  services:
    - id: minecraft1
      name: mc
      host: join.brim.ml
      port: 25565
      proto: _tcp
      service: _minecraft
