- id: msk-homelab1
  domains:
    - id: rip
      name: tie.rip
  hosts:
    - id: falcon
      name: falcon
      addresses:
        - id: wan
          value: 2a01:4f8:222:1618::1
        - id: wan4
          value: 213.133.111.103
    - id: eerie
      name: eerie
      addresses:
        - id: lan
          value: 2a02:2168:8ef4:1500::1
        - id: wan
          value: 2a02:2168:a0f:bd94::2
    - id: akane
      name: akane
      addresses:
        - id: wan
          value: 2a02:2168:a0f:bd94::1
        - id: wan4
          value: &akane4 178.140.50.38
    - id: akane4
      name: akane4
      addresses:
        - id: wan4
          value: *akane4
    - id: saitama
      name: saitama
      addresses:
        - id: lan
          value: 2a02:2168:8edf:2300:f22f:74ff:fe33:727d
    - id: kazuma
      name: kazuma
      addresses:
        - id: lan
          value: 2a02:2168:8edf:2300:642:1aff:fe24:7cf1

  aliases:
    - id: root
      host: akane.@
    - id: jellyfin
      name: jellyfin
      host: saitama.@
    - id: sonarr
      name: sonarr
      host: saitama.@
    - id: radarr
      name: radarr
      host: saitama.@
    - id: prowlarr
      name: prowlarr
      host: saitama.@
    - id: flood
      name: flood
      host: saitama.@
    - id: brim
      name: brim
      host: join.brim.su

  services:
    - id: minecraft1
      name: mc
      host: join.brim.su
      port: 25565
      proto: _tcp
      service: _minecraft
