- id: msk-homelab1
  domains:
    - id: rip
      name: tie.rip
  hosts:
    - id: eerie
      name: eerie
      addresses:
        - id: lan
          value: 2a02:2168:8ecb:6d00::1
        - id: wan
          value: 2a02:2168:a0f:bc6b::1

    #- id: ubernet
    #  name: ubernet
    #  addresses:
    #    - id: wan
    #      value: 2a02:2168:a0f:b1d7::1
    #    - id: wan4
    #      value: 95.84.153.149

    - id: madara
      name: madara
      addresses:
        - id: lan
          value: 2a02:2168:8ecb:6d00::469
        - id: wlan
          value: 2a02:2168:8ecb:6d04::1

    - id: saitama
      name: saitama
      addresses:
        - id: lan
          value: 2a02:2168:8ecb:6d00::7c9
    - id: kazuma
      name: kazuma
      addresses:
        - id: lan
          value: 2a02:2168:8ecb:6d00::6f7

  aliases:
    - id: root
      host: saitama.@
    - id: jellyfin
      name: jellyfin
      host: saitama.@
    - id: sonarr
      name: sonarr
      host: saitama.@
    - id: brim
      name: brim
      host: brim.ml

  services:
    - id: minecraft1
      name: mc
      host: brim.ml
      port: 25565
      proto: _tcp
      service: _minecraft
