name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  polumi-update:
    name: Pulumi Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Install Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version-file: .go-version

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v4.2.2
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: polumi-update-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: polumi-update-${{ runner.os }}-go-

      - name: Run pulumi up
        uses: pulumi/actions@v4.0.0
        with:
          command: up
          stack-name: main
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
