name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  polumi-update:
    name: Pulumi Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.6

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: polumi-update-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: polumi-update-${{ runner.os }}-go-
      # We run tidy after download because download and tidy produce different go.sum.
      # See https://github.com/golang/go/issues/35832
      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Run pulumi up (test)
        uses: pulumi/actions@v3.3.0
        with:
          command: up
          stack-name: test
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run pulumi up (main)
        uses: pulumi/actions@v3.3.0
        with:
          command: up
          stack-name: main
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
