name: CI
on:
  pull_request_target:

jobs:
  polumi-preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          # https://github.com/actions/checkout/issues/518
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version-file: .go-version

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v3.2.6
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: polumi-preview-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: polumi-preview-${{ runner.os }}-go-

      - name: Run pulumi preview
        uses: pulumi/actions@v4.0.0
        with:
          command: preview
          stack-name: main
          comment-on-pr: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
