name: Pulumi Preview
on:
  pull_request_target:

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          # https://github.com/actions/checkout/issues/518
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.6

      - name: Run pulumi preview
        uses: pulumi/actions@v3.3.0
        with:
          command: preview
          stack-name: main
          comment-on-pr: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
