name: Pulumi Update
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.6

      - name: Run pulumi up
        uses: pulumi/actions@v3.3.0
        with:
          command: up
          stack-name: main
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
